### ISSUE TITLE
MeetingList

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#1]
## Value Proposition

- As a dog owner
- I want to see a list with information and a detailed view about scheduled dogdates
- in order to be able get an overview of possible dog dates I could join

## Description

![Image](https://user-images.githubusercontent.com/123748272/227508521-bceaa0a4-61c1-4783-88bf-243e87d8e80e.png)

## Acceptance Criteria

- [x] a list with entries (components/MeetingEntry) of scheduled dates (components/MeetingList) is shown
- [x] the list has a headline "Geplante Dates"

entries should show:
- [x] location
- [x] date
- [x] time
- [x] count of attending dog(s) with dog icon (to have some fun and make it look cute!)

- [x] when no dog dates are scheduled, list is empty and showing text beneath headline as in screen 3 "Noch keine Dates geplant".

- [x] when clicking on list entry user should be directed to MeetingDetail
- [x] When more than one dog is attending, show List of attendees (components/DogName)

- [x] MeetingDetail should have a Link "all Dates" to redirect back to MeetingList

## Tasks

- [x] create feature branch
- [x] add further entries and id-property to dummy data
- [x] adit dummy data to have array of attending Dogs
- [x]  refactor MeetingDetail to have a List of attending dogs (components/DogList)
- [x] create Component DogList that renders component/DogName for each attending dog
- [x] create component/MeetingList
- [x] create component/MeetingEntry
- [x] create page [id].js
- [x] Link index.js with [id].js: when clicking on MeetingEntry in MeetingList the MeetingDetail for the corresponding data-object should be displayed
- [x] write test if list is rendered on screen
- [x] write test if list contains db.length MeetingEntries

**Comment by alexWaligorski** [comment]
I changed component names to: MeetingList, MeetingEntry and MeetingDetail.

**Comment by PReichetanz** [comment]
Regarding your tests: sound good, but we don't test links because they are provided by a library (in this case, Nextjs); testing redirects would rather be a test case for end-to-end-testing.

**Comment by alexWaligorski** [comment]
Thanks Paul! I removed the mentioned tests.
