### ISSUE TITLE
Create DogProfile

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#10]
## Value Proposition

- As a dog owner
- I want to crerate a profile for my dog
- in order to display information about my dog and its preferences 

## Description

![Image](https://user-images.githubusercontent.com/123748272/230344663-17c53a53-3296-4035-a67e-512f24858992.png)

## Acceptance Criteria

- [x] When no dog profile has been added, yet, the profile page shows a button "Profil anlegen"
- [x]  clicking on the button renders a form where the user can fill in the required information
- [x] The form should have inputs for the following information: dog name, dog age, dog preferences (exclusion criteria for walks), dog gender, status of castration, owner's name
- [x] when the dog is female and not castrated an input should be rendered to determin whether the dog is currently in heat (läufig)
- [x] clicking on submit shows the recently added dog profile

## Tasks

- [x] create "Profil anlegen" link which directs to new-profile.js 
- [x] create new-profile.js page 
- [x] create component ProfileForm and render it in profile.js 
- [x] write test to see if the submit handler in Profile Form is called with the correct data

**Comment by supernova-97** [comment]
Nice one again!
Just curious about the button: Is it gonna be one of those button that switches sides when you click it?
If yes, how would you execute that? (asking for my own project hehe)
