### ISSUE TITLE
Update DogProfile

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#11]
## Value Proposition

- As a dog owner
- I want to edit my existing dog profile
- in order to change information about my dog and its preferences 

## Description

![Image](https://user-images.githubusercontent.com/123748272/230373905-f4b9d8a0-911d-471e-8fee-efe229991a3f.png)

## Acceptance Criteria

- [x] The DogProfile has a button "Profil bearbeiten"
- [x]  clicking on the button renders a form which is already filled with the information of the already existing dog profile
- [x] The user can change existing information
- [x] clicking on submit shows the recently updated DogProfile

## Tasks

- [x] create edit.js page which renders the ProfileForm
- [x] refactor the ProfileForm to accept default data
- [x] write function to update form
- [x] write test to see if form is rendered with default data

**Comment by LuYujin9** [comment]
looks great! every dog hat his own profile. If a owner has more dogs, is it possible to show all of them in this page?

By the way ,a small typo : "write tets(test) to see if form is rendered with default data".

**Comment by alexWaligorski** [comment]
Hey Jin, thanks! Yeah, you are right but I think this would be in another story. Becasue, the you would have to fill out the form twice or at least a section of it. I really want to finish my CRUD operations and apply some cooler logic to combine the meetings/ dates with the profile. If I added more logic to the dog profile I would never leave writing forms and generating CRUD operations 😵
