### ISSUE TITLE
Delete DogProfile

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#14]
## Value Proposition

- As a dog owner
- I want to delete my existing dog profile
- in order to remove my personal data from the app

## Description

![Image](https://user-images.githubusercontent.com/123748272/230388531-28946c04-0a90-4b0b-94a4-ad3cbab2e078.png)

## Acceptance Criteria

- [x] The DogProfile has a button "löschen"
- [x]  clicking on the button deletes the already existing dog profile
- [x] The empty profile page shows a button "Profil anlegen"

## Tasks

- [x] create edit.js page which renders the ProfileForm
- [x] write function to delete profile from state

**Comment by dennisbuchwald** [comment]
Hey Alex, great story. A lot has already happened with your app. I'm thrilled and still find the idea super cool! 😊

Would it be helpful before the button actually deletes, to make a security question "Do you really want to delete your profile" to prevent that one clicks on it accidentally?

**Comment by alexWaligorski** [comment]
Dennis, thanks so much! This makes a whole lot of sense from UX perspective! I will write another story for this and implement it a bit later, when I have tackled more of my apps logic. I feel like this is something to vamp up the delete feature with. Does this get your approval 😉 ?
