### ISSUE TITLE
MeetingDetail

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#2]
## Value Proposition

- As a dog owner
- I want to see information about scheduled dogdates
- in order to be able to join and meet other dogowners /dogs

## Description

![Image](https://user-images.githubusercontent.com/123748272/227462453-063e88fc-fff5-4437-8aaf-ffbbbc7dcfc2.png)

## Acceptance Criteria

Detail component should show:

- [x] location (required)
- [x] date (required)
- [x]  time (required)
- [x] attending dog(s) (min. 1 required) with dog icon (to have some fun and make it look cute!)
- [x]  exclusion criteria: dogs falling into these categories shouldn't join (optional)
- [x] when no exclusion criteria are given, field is hidden as in screen 2
- [x] further information concerning the date (optional)
- [x] when no further information is given, field is hidden as in screen 3

## Tasks

- [x] create feature branch
- [x] create component/MeetingDetail
- [x] create component/DogName with name and icon/img
- [x] implement conditional rendering of "exclusion criteria".
- [x] implement conditional rendering of "further information".
- [x] create db.js with 3 Objects: 1x alle info given, 1x without "exclusion criteria", 1x without "further information"
- [x] add Global styles
- [x] write tests to check if location, date, time are rendered on screen
- [x] write tests to check if exclusion criteria and further information are conditionally rendered if data is provided for those elements

**Comment by alexWaligorski** [comment]
Renamed componemt DateDetail to MeetingDetail after comment by coach Paul on User Story DateList concerning the term Date to be a specific term for the Date object in JavaScript which might lead to confusion.
