### ISSUE TITLE
geocoding Location

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#24]
## Value Proposition

- As a dog owner
- I want to freely select a location 
- in order to to see the location of my DogDate on a map

## Description

![Image](https://user-images.githubusercontent.com/123748272/232480861-2af4f354-50f7-461b-b595-69cc254b3ace.png)

## Acceptance Criteria

- [ ] The MeetingDetail Form has a textinput where I can type in a location
- [ ]  While typing matching location-results appear in a field below the location-input
- [ ] When submitting the form, the DetailPage of this meeting is shown with a map on the top and a pin with the location

## Tasks

- [ ] create components/locationSearch with inputfield and section of corresponding results + hidden field for position coordinates
- [ ] fetch nominatim / openstreetmap API via SWR 
- [ ] use input-field text as query-parameter for fetch
- [ ] add onSelect handler to result-items: use position of selected item as value for hidden position field, use name of result value as value for text-input
- [ ] add long, lat props to meeting model in store

**Comment by alinawinter** [comment]
Looks good to me! :-)
