### ISSUE TITLE
MeetingForm

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#3]
## Value Proposition

- As a dog owner
- I want to be able to schedule "meetings" for my dog walks
- in order to let other people join me and my dog

## Description

![Image](https://user-images.githubusercontent.com/123748272/228690644-50c1e472-299c-4083-bce8-f773d885e4ab.png)

## Acceptance Criteria

- [x] MeetingList has button "Neues Date anlegen" components/AddMeetingButton
- [x] click on button "Neues Date anlegen" directs to page edit.js
- [x] new-meeting.js renders components/MeetingForm
- [x] new-meeting.js has Link "alle Dates" redirecting back to MeetingList

MeetingForm should have the following inputs:
- [x] Standort (text input) (required)
- [x] Datum (date input) (required)
- [x] Uhrzeit (time input) (requried)
- [x] Teilnehmende (text input) (required)
- [x] Ausgeschlossen: fieldset with checkboxes for Unkastrierte Rüden, Kastrierte Rüden, Unkatsrierte Hündinnen, Kastrierte Hündinnen, Welpen (all optional)
- [x] Weitere Infos (textarea) (optional)
- [x] Submit Button
- [x] Click on Submit Button "Speichern" redirects to MeetingList
- [x] New MeetingEntry appears as first Entry in MeetingList

## Tasks

- [x] create feature branch
- [x] create pages/create.js 
- [x] create components/NewMeetingButton
- [x] create components/MeetingForm
- [x] implement state to update Meetings
- [x] write test to check if handleSubmit is called on submit

**Comment by supernova-97** [comment]
Looks perfect to me. I'll use this as a template from now on 🙈

**Comment by PReichetanz** [comment]
Tests sound good!

**Comment by alexWaligorski** [comment]
Alright, I modified the tests from before and implemented a simpler one. I spent the day first in Handout / Documentation Hell,  then in Youtube Tutorial hell, later in quite a long, inspiring but fuitile conversation with Chat GPT concerning testing. Yes, I learned a lot but couldnt make my aformentioned tests work. I did not use the discussion board because I made slow progress... as I thought... But finally... I am only testing the submit button. Please Paul, be "nachsichtig"... I will write more complex tests in the future. I swear!
