### ISSUE TITLE
Edit Meeting

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#7]
## Value Proposition

- As a dog owner
- I want to be able to edit already existing "meetings" 
- in order to let other people know that some conditions have changed (e.g. time or date)

## Description

![Image](https://user-images.githubusercontent.com/123748272/229078998-8f519d79-f331-412e-bb9b-302cf0a2a3a5.png)

## Acceptance Criteria

- [x] MeetingDetail has button "bearbeiten"
- [x] click on button "bearbeiten" directs to a page where the meeting detail can be edited in a form
- [x] the form on the edit page has the values of the selected meeting already filled in
- [x] click on "speichern" button saves changes
- [x] after saving changes the current edited meeting is shown with altered data

## Tasks

- [x] create feature branch
- [x] create pages/edit-meeting.js 
- [x] refactor existing button component to be ButtonWithIcon and serve as "speichern", "löschen", "bearbeiten" button with changing colors and icons
- [x] implement routing for "bearbeiten" button -> pages/edit-meeting.js
- [x]  render components/NewMeetingForm with input-values of current components/MeetingDetail already filled in
- [x] use "immer" to easily change data in nested meeting object/data
- [x] write test to check if handleSubmit is called on submit
- [x] write test to check if altered information is submitted by form

**Comment by alinawinter** [comment]
Looks really cool and absolutely thought through to me!! (even though, I'm not very familiar with editing/immer yet, I must admit) I noticed that in "Acceptance Criteria" there is partly a more detailed description on the tasks or what is running in the background than under tasks. Maybe for organisational purposes it would make sense to focus on functionality from the user perspective that the image cannot provide under acceptance criteria and transfer some of the detailed info to the tasks.

**Comment by alexWaligorski** [comment]
Hey Alina, this was a very good remark!!!
How about the structure now? Would you say the concerns of acceptance criteria and tasks are separated in better manner?
