### ISSUE TITLE
Delete Meeting

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#8]
## Value Proposition

- As a dog owner
- I want to be able to delete already existing "meetings" 
- in order to let other people know that the meeting won't take place

## Description

![Image](https://user-images.githubusercontent.com/123748272/229082485-5903d2b0-dbbf-4c7a-830b-3eb659316520.png)

## Acceptance Criteria

- [x] MeetingDetail has button "löschen"
- [x] click on button "löschen" redirects to pages/index.js
- [x] after deleting a meeting, the components/MeetingEntry for the corresponding meeting deisappears from components/MeetingList in pages/index.js

## Tasks

- [x] create feature branch
- [x] implement "delete" button
- [x] write test to check if delte button is rendered
