### ISSUE TITLE
DogProfile

### ISSUE THREAD

**Issue by alexWaligorski** [alexWaligorski/capstone-project#9]
## Value Proposition

- As a dog owner
- I want to have a profile for my dog
- in order to display information about my dog and its preferences 

## Description

![Image](https://user-images.githubusercontent.com/123748272/230337337-288472fb-6af0-4673-96d3-7e7ea49278a1.png)

## Acceptance Criteria

- [x] The dog profile has the following information: profile-icon, dog name, dog age, dog preferences (exclusion criteria for walks), dog gender, status of castration, owner's name
- [x] The dog profile can be seen on a profile page
- [x] The profile page can be reached by clicking on the profile icon in the navbar
- [x] When clicking on the calendar icon on the navbar, the user will be directed back to the overview of all dog dates

## Tasks

- [x] implement profile.js page
- [x] create DogProfile component and render it in profile.js
- [x] create and implement navigation with two links "all dates" and "profile"
- [x] write test to check if profile is rendered correctly

**Comment by supernova-97** [comment]
Nicely written and I think it's a very useful feature :)
